# Generated by Django 3.1 on 2020-10-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionTaker', '0002_completegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='completegroup',
            name='is_completed',
            field=models.BooleanField(default=0),
        ),
    ]
