# Generated by Django 3.1 on 2020-10-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionTaker', '0003_completegroup_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=0),
        ),
    ]
