# Generated by Django 3.1 on 2020-10-04 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
        ('questionCreator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='logreg.user'),
        ),
    ]
