# Generated by Django 3.1 on 2020-10-06 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionCreator', '0004_auto_20201005_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionCreator.questiongroup'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionCreator.questiontype'),
        ),
    ]
