# Generated by Django 3.1 on 2020-10-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionCreator', '0005_auto_20201005_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionCreator.questiongroup'),
        ),
    ]
